version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - postgres

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=neondb
      - DB_POSTGRESDB_USER=neondb_owner
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_PUBLIC_API_ENDPOINT=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - N8N_NODE_EXAMPLES_ENABLED=true
    volumes:
      - ./workflows:/home/node/.n8n/workflows
    depends_on:
      - backend
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_hv3FTfGu5oVm
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
